# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f pre-requirements.txt ]; then pip install --upgrade -r pre-requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Lint with Black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black .
    - name: Test with pytest
      run: |
        pytest .
    - name: Check with mypy
      run: |
        mypy . --show-error-codes --config-file mypy.ini
